### ISSUE TITLE
Upgrade to new dribbble api

### ISSUE THREAD

**Issue by thehonestape** [martinbean/dribbble-php#13]
any plans in the works to upgrade this for the new api? 

just realized my feed broke today after they shut down endpoints for the beta api.  oops!

**Comment by martinbean** [comment]
@thehonestape Sorry to hear that.

I did make a start on re-writing this library for the new API, but client work got the better of me. I’ll look to pick this up again this weekend.

**Comment by nielsvr** [comment]
@martinbean any updates on this :)? Is there a list on changes so that we can help?

**Comment by martinbean** [comment]
@thehonestape @nielsvr I’ve re-written the library to use the new Dribbble API.
